### ISSUE TITLE
Wait until the state of an UI Control

### ISSUE THREAD

**Issue by jberthe** [NoriSte/cypress-wait-until#122]
Hello,

I'm new in CyPress and with your plugin. I try to use it with SAPui5 framework, and all control have getBusy() function to indicate if the control is beeing working or not.

I want to use your plugin but I do not know how to do it.

here is my tries :

`cy.waitUntil(() => {
    cy.get('#id').then((oControl) =>{
        oControl.control()[0].getBusy() === true

})`

It's seams doesn't work. Maybe it is because of the syntaxe...

Please advice.

Regards,
Joseph

**Comment by NoriSte** [comment]
Hi @jberthe 

The function that you are passing to `waitUntil` does not return anything. Add `return` before `cy.get`

```js
cy.waitUntil(() => {
  return cy.get('#id').then((oControl) => {
    return oControl.control()[0].getBusy() === true
  })
})
```
or you could omit the `return` if you omit the brackets
```js
cy.waitUntil(() => cy.get('#id').then((oControl) => oControl.control()[0].getBusy() === true))
```

Not so important: `.getBusy() === true` is useless since `getBusy` already returns a `boolean`. Simplest version is
```js
cy.waitUntil(() => cy.get('#id').then((oControl) => oControl.control()[0].getBusy()))
```

Let me know if it works 😉

**Comment by jberthe** [comment]
Hey :) thanks it's working fine like this !
Many thanks.
Joseph

**Comment by NoriSte** [comment]
You're welcome 😊
