### ISSUE TITLE
Add Optional Support to avoid failing a test

### ISSUE THREAD

**Issue by bhaskerchari** [NoriSte/cypress-wait-until#128]
Is it possible to fail silently or ignore the error so that if cy.waitUntil() condition is not satisfied at all and is timedout but still the test is not failed and still want to proceed further with the execution?

I believe I have gone through the documentation but haven't found a way if this can be achieved. The usecase may not be regular but still I have ended up with such case.

So I think it would be nice if there is a way possible by setting a config param which will avoid the test to fail and allow it to proceed further eventhough the cy.waitUntil() condition is not met.

Another option could be to have an optional onTimedOut() callback let's say to be triggered on time out and which is expected to return a Boolean value which will decide whether to pass or fail cy.waitUntil() finally.

I hope this does make sense to have some kind of control to pass or fail cy.waitUntil().

**Comment by NoriSte** [comment]
Hi @bhaskerchari 
I could have added this capability but I avoided doing that. I chose to do so because [Cypress enforces to avoid conditional testing](https://docs.cypress.io/guides/core-concepts/conditional-testing.html) and that's why I prefer to stay with them instead of adding this capability.

I understand that there are cases where conditional testing makes sense but if add this capability everyone will use this plugin to create conditional tests, treating the Cypress feature (because avoiding conditional testing is a feature) as "a bug".

What could you do? You could write your own recursive promise check function (take a look [here](https://stackoverflow.com/questions/54883861/how-can-i-wait-for-each-element-in-a-list-to-update-to-a-certain-text-using-cypr/55363629#55363629) and [here](https://stackoverflow.com/questions/54732818/how-do-i-wait-until-a-cookie-is-set/54743229#54743229) where I explain how to do that) where you manage your case. After all, `cy.waitUntil` is just a recursive promise manager 😊

**Comment by bhaskerchari** [comment]
@NoriSte ,

It does make sense what you have mentioned and I have figured out the solution for my problem by simply putting an or condition and checking for some other condition to be satisfied in addition to existing check I was doing.

Thanks for the reference urls it may help be some other time :)

**Comment by NoriSte** [comment]
You're welcome 😊
