### ISSUE TITLE
Directly throws an error message

### ISSUE THREAD

**Issue by robinfriedmann** [NoriSte/cypress-wait-until#14]
Hey,
```
    cy.waitUntil(()=> {
      cy.get('button[data-tip=btn_aim]')
        .then($el=>{
          return (!$el.attr('disabled'));
        })
    });
```
I always get an Errormsg.

![image](https://user-images.githubusercontent.com/22767753/59034616-a73a3a00-886b-11e9-9e0f-8b6866e203ba.png)

**Comment by NoriSte** [comment]
Hi @robinfriedmann 
First of all: is the disabled attribute of the button removed after a while in your app? Or the plugin times out because the `disabled` attribute always exists?

One more thing: you don't need to use the `cypress-wait-until` plugin for something like this, you could just write
```javascript
cy.get('button[data-tip=btn_aim]').should('not.have.attr', 'disabled')
```
and Cypress will retry until the `disabled` attribute disappears.

Let me know if I can help you more.
Stefano

**Comment by NoriSte** [comment]
Did you solve the problem Robin? I close the PR but feel free to reopen it if you need more support 😉
