### ISSUE TITLE
Do not support async/await function in es6 style

### ISSUE THREAD

**Issue by huqiaohua** [NoriSte/cypress-wait-until#158]
`cy.waituntill` would not execute in an async function, otherwise, you use `.then`

**Comment by NoriSte** [comment]
Remember that [cypress commands are not promises](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html) and [you can't use async/await]( https://github.com/cypress-io/cypress/issues/1417) in Cypress tests.

Feel free to reopen the issue if you think that your problem is unrelated to the mentioned posts and in case provide an example and a repo to play with, please.

Thanks 😊
