### ISSUE TITLE
snapshots can't be used in combination with this plugin?

### ISSUE THREAD

**Issue by symon-skelly** [NoriSte/cypress-wait-until#171]
I am using the following cypress plugin to assert DOM elements to reduce the amount of convoluted steps that must be taken to assert on specific elements of the application under test.

https://github.com/cypress-io/snapshot

I use cy.waitUntil() in many other areas of the testing suite, but for some reason the snapshot feature seems to not like the waitUntil functionality, the snapshot will be checked once, and only once, and if it fails, the waitUntil will not kick into action.

Example code snippet:

`cy.waitUntil(() => cy.get('.modal-header').snapshot({name: modelHeader-T001'}))`

Is this expected, or am I doing something wrong here?

**Comment by NoriSte** [comment]
Hi @symon-skelly 
You cannot use it inside `waitUntil` because the snapshot plugin throws an error if the snapshot does not match. Take a look at [the previous answer](https://github.com/NoriSte/cypress-wait-until/issues/159#issuecomment-649678691) I gave you, it's short but contains the all the needed links 😉
