### ISSUE TITLE
.click() not being retried

### ISSUE THREAD

**Issue by VickyLund** [NoriSte/cypress-wait-until#191]
I am trying to retry a button click that fails randomly with the error "Timed out retrying: `cy.click()` failed because this element is detached from the DOM.".

I have figured out the way to use `waitUntil` to solve my problem but I want to understand why my first approach did not work.

Initial approach. This fails after first retry:
`cy.waitUntil(() =>
        cy.wrap(Cypress.$(ctaLocatorName)).click().then(
          () => Cypress.$("#getArea").length > 0
        )
    );`

Though if I convert it to below snippet, it works fine:
`cy.waitUntil(() =>
        cy.wrap(Cypress.$(Cypress.$(ctaLocatorName).click())).then(
          () => Cypress.$("#getArea").length > 0
        )
    );
`

**Comment by NoriSte** [comment]
Hi @VickyLund 
Take a look at this Cypress issue for more info 😉
cypress-io/cypress#7306

**Comment by VickyLund** [comment]
Hi @NoriSte 

Thanks for the quick reply. This is, in fact, the link where I discovered your plugin!

But my question is a bit different.

I understand why cy.get("...") doesn't work here.
But why doesn't my Cypress click work here? I had to use jquery click instead.

Cypress.$(ctaLocatorName)).click()
Cypress.$(Cypress.$(ctaLocatorName).click())

**Comment by NoriSte** [comment]
Because `cy.click` works on a "previous" version of the DOM element (that could be detached meanwhile) while jQuery' click works on the just queried DOM element, the existing one. `cy.click` can't work but, moreover, it contains [an inner assertion](https://docs.cypress.io/api/commands/click.html#Assertions) that checks for the actionable state of the element and makes the test fail if the element is not actionable.

If it's not enough clear, please let me know 😊

**Comment by VickyLund** [comment]
Thanks a lot!
