### ISSUE TITLE
Is version 2.0.1 compatible with cypress 10?

### ISSUE THREAD

**Issue by ltimothy7** [NoriSte/cypress-wait-until#476]
[Question in title]

Thanks so much

**Comment by NoriSte** [comment]
yes, it is 😊 have you encountered any problems?

**Comment by ltimothy7** [comment]
Thank you @NoriSte 
Sorry for the late response

While I cannot give the exact code from work, our logic is similar to:

`cy.wrap(null) 
      .then(//make cy request and store auth token)
      .end()
      .visit(// company website)
      .wait(//60 seconds) // wait for elements to render
      .wrap(null)
      .then(// check that element test shows success and return msg == 'success')
      .then($msg => Boolean($msg)) // capturing this return to avoid error of mixed synch and asynch code
`
Our max time is 75 minutes and we have test the interval from 0 to 2 minutes.

With the above logic, we are encountering two issues in when using cypress 10 with cypress-wait-until 2.0.1:
1. We are getting a V8 out-of memory error.
2. The test unexpectedly fails and passes even though the message does not say 'success'
Could you give any input if our approach is valid?

**Comment by NoriSte** [comment]
Uhm it's hard to reason about it with such an abstract case. I would suggest you to share a minimal repo to play with when you share a minimal example to play with, that could be
1. Calling an open API
2. Loading a website that's not yours
3. Reducing the wait from 60 seconds to 1
4. etc.

otherwise I can't help. Also, what happens in the page during the 60 seconds? Your case is an extreme edge case which problems (I think) are not related to waitUntil...

Because of this I close the PR but feel free to reopen it if you think there is something to check on waitUntil side. Also, I suggest you sharing your problem on Cypress Discord's server :)
